defaults:
  - _self_
  - simulation: sl_basic
  - reconstruction: zero_filled
  - stats: stat_default

save_data: false

hydra:
  job:
    chdir: true

  callbacks:
    multirun_callbacks:
      _target_: simfmri.hydra.callback.MultiRunGatherer
