defaults:
  - _self_
  - simulation: sl_basic
  - reconstruction: zero_filled
  - stats: stat_default

save_data: "mini"

hydra:
  job:
    chdir: true

  callbacks:
    gather_files:
      _target_: simfmri.hydra.callback.MultiRunGatherer
    latest_link:
      _target_: simfmri.hydra.callback.LatestRunLink
