### Simulation for a Shepp Logan phantom with activation.
_target_: simfmri.simulator.SimulationDataFactory
checkpoints: false
sim_params:
  _target_: simfmri.simulator.SimulationParams
  n_frames: 100
  shape: [128, 128, 128]
  TR: 1.0
  n_coils: 1

handlers:
  generator:
    _target_: simfmri.simulator.SheppLoganGeneratorHandler
  activation:
    _target_: simfmri.simulator.ActivationHandler.from_block_design
    event_name: block_on
    block_on: 3
    block_off: 3
    duration: ${simulation.sim_params.n_frames}
    offset: 0
  slicer:
    _target_: simfmri.simulator.SlicerHandler
    axis: 0
    index: 58
  noise:
    _target_: simfmri.simulator.GaussianNoiseHandler
    snr: 1000
  acquisition:
    _target_: simfmri.simulator.AcquisitionHandler.vds
    acs: 24
    accel: 4
    accel_axis: 1
    constant: true
    gen_smaps: false
  # noise:
  #   _target_: simfmri.simulator.KspaceNoiseHandler
  #   snr: 1000
