defaults:
  - _self_
  - simulation: sl_basic
  - reconstruction: zero_filled
  - stats: stat_default

save:
  data: "mini"
  compress: true
hydra:
  job:
    chdir: true

  callbacks:
    gather_files:
      _target_: simfmri_runner.callback.MultiRunGatherer
    latest_link:
      _target_: simfmri_runner.callback.LatestRunLink
