defaults:
  - _self_
  - simulation: big_basic
  - reconstruction: zero_filled
  - stats: stat_default
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

dry_mode: false
save:
  data: "mini"
  compress: true

hydra:
  job:
    chdir: true
  callbacks:
    gather_files:
      _target_: hydra_callbacks.MultiRunGatherer
    latest_link:
      _target_: hydra_callbacks.LatestRunLink
    perf:
      _target_: hydra_callbacks.ResourceMonitor
