
### Simulation using the BIG defined phantom with activation.
_target_: simfmri.runner.factory.SimulationDataFactory
checkpoints: false
sim_params:
  sim_tr: 0.2
  sim_time: 300
  shape: [256, 256]
  n_coils: 1
  rng: 19980408
handlers:
  generator:
    _target_: simfmri.simulator.BigPhantomGeneratorHandler
  generator2:
    _target_: simfmri.simulator.RoiDefinerHandler
  generator3:
    _target_: simfmri.simulator.TextureAdderHandler
  activation:
    _target_: simfmri.simulator.ActivationHandler.from_block_design
    event_name: block_on
    block_on: 20
    block_off: 20
    duration: 100
  noise:
    _target_: simfmri.simulator.GaussianNoiseHandler
    snr: 1000
  acquisition:
    _target_: simfmri.simulator.VDSAcquisitionHandler
    base_TR: 2
    acs: 24
    accel: 4
    accel_axis: 1
    constant: false
    smaps: false
    direction: center-out
  # noise:
  #   _target_: simfmri.simulator.KspaceNoiseHandler
  #   snr: 1000
