
### Simulation using the BIG defined phantom with activation.
_target_: simfmri.runner.factory.SimulationDataFactory
checkpoints: false
sim_params:
  sim_tr: 0.1
  sim_time: 300
  shape: [192,192]
  n_coils: 8
  rng: 19980408
handlers:
  generator:
    _target_: simfmri.simulator.BigPhantomGeneratorHandler
  generator2:
    _target_: simfmri.simulator.RoiDefinerHandler
  generator3:
    _target_: simfmri.simulator.TextureAdderHandler
  activation:
    _target_: simfmri.simulator.ActivationHandler.from_block_design
    event_name: block_on
    block_on: 20
    block_off: 15
    duration: 300
    bold_strength: 0.02
  noise:
    _target_: simfmri.simulator.GaussianNoiseHandler
    snr: 1000
  acquisition:
    _target_: simfmri.simulator.VDSAcquisitionHandler
    shot_time_ms: 25
    acs: 0.125
    accel: 4
    accel_axis: 1
    constant: false
    direction: center-out
  # noise:
  #   _target_: simfmri.simulator.KspaceNoiseHandler
  #   snr: 1000
