defaults:
  - _self_
  - simulation: big_basic
  - reconstructors: zero_filled
  - stats: stat_default
  - override hydra/job_logging: colorlog
  - override hydra/hydra_logging: colorlog

dry_mode: false
save: false
cache_dir: null
# save:
#   data: "mini"
#   compress: true

hydra:
  job:
    chdir: true

  callbacks:
    gather_files:
      _target_: hydra_callbacks.MultiRunGatherer
      aggregator:
        _partial_: true
        _target_: simfmri.cli.utils.aggregate_results

    latest_run:
      _target_: hydra_callbacks.LatestRunLink
