# This files contains the configuration to reproduce the scenario 2 of the Simfmri paper.

force_sim: false
cache_dir: ${oc.env:PWD}/cache
result_dir: ${oc.env:PWD}/results

simulation:
  sim_params:
    sim_tr: 0.1
    sim_time: 300
    shape: [42, 64, 64]
    fov: [0.181,0.217,0.181]
    n_coils: 1
    rng: 19980408
    lazy: True
  handlers:
    phantom-brainweb:
      subject_id: 5
      bbox: [0.225,-0.07, 0.06, -0.055, null, null]
    activation-block:
      event_name: block_on
      block_on: 20
      block_off: 20
      duration: 300
      bold_strength: 0.02
    noise-gaussian:
      snr: 100
    acquisition-vds:
      shot_time_ms: 50
      acs: 1
      accel: 1
      accel_axis: 0
      constant: true
      direction: top-down
      smaps: false

reconstructors:
  adjoint: {}
  sequential:
    optimizer: pogm
    wavelet: sym8
    trehsold: sure
    max_iter_per_frame: 15

stats:
  contrast_name: block_on


hydra:
  job:
    chdir: true

  run:
    dir: ${result_dir}/outputs/scenario2/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ${result_dir}/multirun/scenario2/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}

  callbacks:
    gather_files:
      _target_: hydra_callbacks.MultiRunGatherer
      aggregator:
        _partial_: true
        _target_: simfmri.cli.utils.aggregate_results

    latest_run:
      _target_: hydra_callbacks.LatestRunLink
      run_base_dir:  ${result_dir}/outputs
      multirun_base_dir:  ${result_dir}/multirun
