# This files contains the configuration to reproduce the scenario 2 of the Simfmri paper.

force_sim: false
cache_dir: ${oc.env:PWD}/cache
result_dir: ${oc.env:PWD}/results

simulation:
  sim_params:
    sim_tr: 0.1
    sim_time: 300
    shape: [-1,-1,-1] # shape will be determined with the bbox and the brainweb phantom.
    fov: [-1,-1,-1]
    n_coils: 8
    rng: 19980408
    lazy: true
  handlers:
    phantom-brainweb:
      subject_id: 5
      bbox: [0.225,-0.07, 0.06, -0.055, null, null]
      brainweb_folder: ${cache_dir}/brainweb
      res: [1.0, 1.0, 0.943]
    activation-block:
      event_name: block_on
      block_on: 20
      block_off: 20
      duration: 300
      bold_strength: 0.02
    noise-gaussian:
      snr: 100
    acquisition-sos:
      shot_time_ms: 50
      acsz: 0.125
      accelz: 4
      n_samples: 8000
      constant: false
      directionz: center-out
      backend: cufinufft

reconstructors:
  adjoint:
    nufft_backend: cufinufft
    nufft_kwargs: {}
  sequential:
    nufft_backend: cufinufft
    nufft_kwargs: {}
    optimizer: pogm
    wavelet: sym8
    threshold: sure
    max_iter_per_frame: 30

stats:
  contrast_name: block_on


hydra:
  job:
    chdir: true

  run:
    dir: ${result_dir}/outputs/scenario2/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: ${result_dir}/multirun/scenario2/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}

  callbacks:
    gather_files:
      _target_: hydra_callbacks.MultiRunGatherer
      aggregator:
        _partial_: true
        _target_: simfmri.cli.utils.aggregate_results

    latest_run:
      _target_: hydra_callbacks.LatestRunLink
      run_base_dir:  ${result_dir}/outputs
      multirun_base_dir:  ${result_dir}/multirun
